version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql

  php:
    image: wodby/wordpress:4-7.1-3.0.0
    environment:
      ENV: development
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: mariadb
      WP_HOME: localhost:8080
      WP_SITEURL: localhost:8080
    volumes:
      - .:/var/www/html:cached
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  nginx:
    image: wodby/wordpress-nginx:4-1.13-3.0.1
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - php
    ports:
      - '8080:80'

